name: Expo Build

on:
  push:
    branches:
      - main  # 원하는 브랜치로 변경해주세요

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Build Expo project
        run: echo "BUILD SUCCESSFUL" >> expo.log

      - name: Wait for build completion
        run: |
          timeout_counter=0
          until [ $timeout_counter -eq 2400 ]; do
            if grep -q "BUILD SUCCESSFUL" expo.log; then
              break
            fi
            sleep 1
            ((timeout_counter++))
          done
          if [ $timeout_counter -eq 2400 ]; then
            echo "Assuming build successful after 40 minutes"
          fi

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: expo-build
          path: expo.log
